In [1]:
import pandas as pd
import numpy as np
import nltk 
from nltk.corpus import stopwords
import string 

In [2]:
df = pd.read_csv("emails.csv")

In [3]:
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [4]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    5728 non-null   object
 1   spam    5728 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 89.6+ KB


In [6]:
df.describe()

spam
count  5728.000000
mean      0.238827
std       0.426404
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [7]:
df.columns

Index(['text', 'spam'], dtype='object')

In [8]:
df.drop_duplicates(inplace = True)

In [9]:
df.shape


(5695, 2)

In [10]:
# download the stowords package

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SHUBHAM\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [11]:
def process_text(text):
    # remove the punctuation 
    # remove stopwords
    # return a list of clean text words
    
    #1
    nopunc = [char for char in text if char not in string .punctuation]
    nopunc = ''.join(nopunc)
    
    #2
    clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]
    
    #3
    return clean_words

In [12]:
# show the tokenization  (A list of tokens also called lemmas)
df['text'].head().apply(process_text)
# each msg is boken up in token sepreted by comma

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [13]:
# example

message4 = 'hello world hello hello world play' 
message5 = 'test test test test one hello'
print(message4)
print()


# convert the text to a matrix of token counts 

from sklearn.feature_extraction.text import CountVectorizer

bow4 = CountVectorizer(analyzer=process_text).fit_transform([[message4],[message5]])
print(bow4)

print()

print('total  are in the message 4 and message5 number')
print(bow4.shape)

hello world hello hello world play

  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1

total  are in the message 4 and message5 number
(2, 5)


In [14]:
# convert a collecton  of text  to a matxi token
from sklearn.feature_extraction.text import CountVectorizer

message_bow  = CountVectorizer(analyzer  = process_text).fit_transform (df['text'])

In [15]:
# split the data into train and test split

from sklearn.model_selection import train_test_split


In [16]:
x_train,x_test,y_train,y_test = train_test_split(message_bow,df['spam'],test_size = 0.20,random_state = 0)

In [17]:
# get the shape of messages_bow
message_bow.shape

(5695, 37229)

In [19]:
# cteate and trai the naive bayes classifyer 

from sklearn.naive_bayes import MultinomialNB

In [24]:
classifier = MultinomialNB().fit(x_train,y_train)

In [27]:
# print the predictions
print(classifier.predict(x_test))

# print the actual values

print(y_train.values)

[1 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [34]:
# evaluate the model on training datasets 

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(x_train)
print(classification_report(y_train,pred))

print()
print('confusion_matrix: \n',confusion_matrix(y_train,pred))

print('accuracy_score:\n',accuracy_score(y_train,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


confusion_matrix: 
 [[3445   12]
 [   1 1098]]
accuracy_score:
 0.9971466198419666


In [35]:
# print the predictions
print(classifier.predict(x_test))

# print the actual values

print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [36]:
# evaluate the model on training datasets 

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(x_test)
print(classification_report(y_test,pred))

print()
print('confusion_matrix: \n',confusion_matrix(y_test,pred))

print('accuracy_score:\n',accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


confusion_matrix: 
 [[862   8]
 [  1 268]]
accuracy_score:
 0.9920983318700615
